### PR TITLE
Only need to create machine-id, no need to mount

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by mrunalp** [comment]
Should we also remove it on teardown?

**Comment by mrunalp** [comment]
Also, there is no need to set the selinux context (probably it gets the right one as it is under the container rootfs)?

**Comment by rhatdan** [comment]
Yes we should remove it. machine-id will get the context of the parent direcorty (etc) which should be correct.

**Comment by mrunalp** [comment]
Merging this. I will create a follow on PR for removing the file. Thanks!

**Pull request merged**
