### PR TITLE
Cgroup

### PR DESCRIPTION
**Pull request by rhatdan**
Follow on pull request to mount /sys/fs/cgroup into the container, does not work because it causes libcontainer to break when it tries to setup cgroups.

### CODE REVIEW

**Comment by mrunalp** [comment]
We can't mount /sys/fs/cgroup as libcontainer will try to mount on top of that. We need a flag that skips the /sys/fs/cgroup mount in libcontainer when it is mounted from outside similar to /dev handling.

**Comment by mrunalp** [comment]
The rest looks good to me. I will try it out once and then merge it. Thanks!

**Comment by rhatdan** [comment]
Yes we have to figure out a solution to the cgroup fs problem, it is actually must worse.  I talked to Lennart about it and he says we need to walk the cgroup tree and mount all of the mounts as Read/Only, to stop systemd from mucking around with them.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
