### PR TITLE
specfile changes

### PR DESCRIPTION
**Pull request by lsm5**
- updates to specfile such that rpmlint is happy
- specified arches as per docker
- added dependency on docker

the specfile will/should go away from this repo once the package is accepted
into Fedora, but this is a good home until then.

Signed-off-by: Lokesh Mandvekar lsm5@fedoraproject.org

@mrunalp don't know if we should even care to merge this. Just an FYI RE: fedora rpm review.

### CODE REVIEW

**Comment by lsm5** [comment]
fedora review at https://bugzilla.redhat.com/show_bug.cgi?id=1290523

**Comment by mrunalp** [comment]
@lsm5 Yeah, no issues in merging this as long as it works for you :)

**Comment by lsm5** [comment]
i'll make a final PR to remove this file once we have it approved in Fedora. Keep this open until then I guess :)

**Comment by mrunalp** [comment]
Sounds good :)

**Comment by rhatdan** [comment]
I am trying to hook up a make srpm to Makefile.am, but make dist builds oci-systemd-hook-0.1.3.tar.gz But with this patch the spec file is looking for hooks0-ebdb622.tar.gz

rpmbuild -ba oci-systemd-hook.spec 
error: File /home/dwalsh/sources/SOURCES/hooks-ebdb622.tar.gz: No such file or directory

I would expect the tar ball to be closer to the first name then the second.

**Comment by rhatdan** [comment]
If I copy the dist file to this location, I get 

```
rpmbuild -ba oci-systemd-hook.spec Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.HFifKW
+ umask 022
+ cd /home/dwalsh/sources/BUILD
+ cd /home/dwalsh/sources/BUILD
+ rm -rf hooks-ebdb622b137884c71c89d8a61688408ce68fd93e
+ /usr/bin/gzip -dc /home/dwalsh/sources/SOURCES/hooks-ebdb622.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd hooks-ebdb622b137884c71c89d8a61688408ce68fd93e
/var/tmp/rpm-tmp.HFifKW: line 37: cd: hooks-ebdb622b137884c71c89d8a61688408ce68fd93e: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.HFifKW (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.HFifKW (%prep)
```

**Pull request merged**
