### PR TITLE
Skip hook mounts when already specified in config

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel mrunalp@gmail.com

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
@nalinp @rhvgoyal  is there a simple way to check if a target is already a mount point?

@mrunalp Problem with this is there are other mountpoints that we probably want to avoid /var/log/journal and maybe if we add it in the future /sys/fs/cgroup, perhaps even /etc/machine-id.

**Comment by rhvgoyal** [comment]
Parse /proc/self/mountinfo and figure out if target is already mounted. docker mount package exports Mounted() to figure it out. But now this is C code so we can't use that package as it is. So may be write a helper function to parse /proc/self/mountinfo.

**Comment by mrunalp** [comment]
At the point the hook is called, nothing is mounted under the container root yet. We only have a config for what will be mounted as part of container setup after the hook is done so I went this route.

**Comment by rhvgoyal** [comment]
ok, makes sense. If nothing is mounted yet, you have to parse config.

**Comment by rhatdan** [comment]
Ok parse config for all mount points in systemhooks and pass in blocked mount points, is the best we can do.  BTW Will this code need to change when we pass data from runc versus from docker?

**Comment by mrunalp** [comment]
Yes, I will make the changes. It will have to change to parse the OCI config instead of docker config. This is a stop gap till there is docker runc integration.

**Comment by mrunalp** [comment]
@rhatdan Updated.

**Comment by rhatdan** [comment]
LGTM.

**Comment by mrunalp** [comment]
@rhvgoyal I have addressed all comments.

**Comment by rhvgoyal** [comment]
@mrunalp thanks for the changes. LGTM.

**Pull request merged**
