### PR TITLE
Add a rpm spec file

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel mrunalp@gmail.com

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan I tested this on F23. PTAL.

**Comment by mrunalp** [comment]
@rhatdan I added man page, update README.md and added the docs to the spec file.

**Comment by rhatdan** [comment]
```
rpmlint oci_systemd_hook.spec 
oci_systemd_hook.spec: E: specfile-error warning: bogus date in %changelog: Mon Nov 22 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.2
oci_systemd_hook.spec: E: specfile-error warning: bogus date in %changelog: Mon Nov 22 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.3
oci_systemd_hook.spec: E: specfile-error warning: bogus date in %changelog: Mon Nov 22 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.2
0 packages and 1 specfiles checked; 3 errors, 0 warnings.
```

**Comment by rhatdan** [comment]
make dist builds
oci-systemd-hook-0.1.tar.gz
But
rpmbuild -bs oci_systemd_hook.spec 
error: File /home/dwalsh/sources/SOURCES/v0.1.3.tar.gz: No such file or directory

Those should match.

**Comment by rhatdan** [comment]
```
diff --git a/configure.ac b/configure.ac
index 2565b6c..9232ef5 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,4 +1,4 @@
-AC_INIT([OCI Systemd Hook], 0.1)
+AC_INIT([OCI Systemd Hook], 0.1.3)
 AC_CONFIG_AUX_DIR([build-aux])
 AC_CONFIG_HEADERS([config.h])
 AM_INIT_AUTOMAKE([foreign -Wall -Werror subdir-objects])
diff --git a/oci_systemd_hook.spec b/oci_systemd_hook.spec
index 7428e34..2659c33 100644
--- a/oci_systemd_hook.spec
+++ b/oci_systemd_hook.spec
@@ -5,7 +5,7 @@ Summary:        OCI systemd hook for docker
 Group:          Applications/Text
 License:        GPLv3+
 URL:            https://github.com/mrunalp/hooks
-Source:         https://github.com/mrunalp/hooks/archive/v%{version}.tar.gz
+Source:         https://github.com/mrunalp/hooks/archive/%{name}-%{version}.tar.gz

 BuildRequires:  autoconf
 BuildRequires:  automake
@@ -34,9 +34,9 @@ make %{?_smp_mflags}
 %doc README.md LICENSE

 %changelog
-* Mon Nov 22 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.2
+* Mon Nov 23 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.3
 - Fix bug in man page installation
-* Mon Nov 22 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.3
+* Mon Nov 23 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.2
 - Add man pages
-* Mon Nov 22 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1.2
+* Mon Nov 23 2015 Mrunal Patel <mrunalp@gmail.com> - 0.1-1
 - Initial RPM release
```

**Comment by mrunalp** [comment]
The naming weirdness is partly due to repo name being hooks. I will fix that.

**Comment by mrunalp** [comment]
@rhatdan I have addressed the comments. Also, renamed the package to have - in name instead of _ so that it works with make dist.

**Comment by rhatdan** [comment]
LGTM.  Now you get to start doing the hard part.  Working it through the Fedora process.

BTW have you ever looked into the /proc/fs/cgroup problems?

**Comment by mrunalp** [comment]
@rhatdan Thanks for the review. Agree that is going to be the hardest :laughing: 
I did spend some time but it isn't done. I will get back to looking into the cgroups mounting.

**Pull request merged**
