### PR TITLE
Add selinux label to /run

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel mrunalp@gmail.com

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan PTAL.

**Comment by rhatdan** [comment]
Add an selinux.SelinuxEnabled() check so that it will work on SELinux disabled machines.

**Comment by mrunalp** [comment]
@rhatdan Yes, I will add that.

**Comment by mrunalp** [comment]
@rhatdan Updated.

**Pull request merged**
